package com.ooad.good.mapper;

import com.ooad.good.model.po.Coupon_spuPo;

public interface Coupon_spuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int insert(Coupon_spuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int insertSelective(Coupon_spuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    Coupon_spuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coupon_spuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coupon_spuPo record);
}