package com.ooad.good.mapper;

import com.ooad.good.model.po.Fash_salePo;

public interface Fash_salePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    int insert(Fash_salePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    int insertSelective(Fash_salePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    Fash_salePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Fash_salePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fash_salePo record);
}