package com.ooad.good.mapper;

import com.ooad.good.model.po.Flash_sale_itemPo;

public interface Flash_sale_itemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int insert(Flash_sale_itemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int insertSelective(Flash_sale_itemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    Flash_sale_itemPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Flash_sale_itemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Flash_sale_itemPo record);
}