package com.ooad.good.mapper;

import com.ooad.good.model.po.Float_pricePo;

public interface Float_pricePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int insert(Float_pricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int insertSelective(Float_pricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    Float_pricePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Float_pricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Float_pricePo record);
}