package com.ooad.good.mapper;

import com.ooad.good.model.po.Goods_skuPo;

public interface Goods_skuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insert(Goods_skuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insertSelective(Goods_skuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    Goods_skuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goods_skuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods_skuPo record);
}