package com.ooad.good.mapper;

import com.ooad.good.model.po.Goods_categoryPo;
import com.ooad.good.model.po.Goods_categoryPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Goods_categoryPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int deleteByExample(Goods_categoryPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int insert(Goods_categoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int insertSelective(Goods_categoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    List<Goods_categoryPo> selectByExample(Goods_categoryPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    Goods_categoryPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Goods_categoryPo record, @Param("example") Goods_categoryPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Goods_categoryPo record, @Param("example") Goods_categoryPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goods_categoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods_categoryPo record);
}