package com.ooad.good.mapper;

import com.ooad.good.model.po.Groupon_activityPo;

public interface Groupon_activityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int insert(Groupon_activityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int insertSelective(Groupon_activityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    Groupon_activityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Groupon_activityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Groupon_activityPo record);
}