package com.ooad.good.mapper;

import com.ooad.good.model.po.ShopPo;
import com.ooad.good.model.po.ShopPoExample;
import java.util.List;

public interface ShopPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int insert(ShopPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int insertSelective(ShopPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    List<ShopPo> selectByExample(ShopPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    ShopPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopPo record);
}