package com.ooad.good.mapper;

import com.ooad.good.model.po.SkuPo;
import com.ooad.good.model.po.SkuPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insert(SkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insertSelective(SkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    List<SkuPo> selectByExample(SkuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    SkuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SkuPo record, @Param("example") SkuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SkuPo record, @Param("example") SkuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SkuPo record);
}